### ISSUE TITLE
Shelly Plus 1 - device not updated

### ISSUE THREAD

**Issue by vquiering** [bieniu/ha-shellies-discovery-gen2#104]
**Describe the bug**
The automations run, get all values, create the device in HASS but doesn't update them. The values are found in the debug logs. The device is not updated though.

**Expected behavior**
Updated values in the device.

**Versions:**
 - Home Assistant: 2022.10.4
 - Shellies Discovery GEN2: v1.6.0
 - Shelly device firmware: 20221014-103904/0.11.3-g0753507

**Shellies Discovery GEN2 automation:**

```yaml
- id: shellies_announce_gen2
  alias: Shellies Announce Gen2
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  action:
  - repeat:
      for_each: '{{ device_ids }}'
      sequence:
      - service: mqtt.publish
        data:
          topic: '{{ repeat.item }}/rpc'
          payload: '{{ device_info_payload }}'
  variables:
    device_info_payload: '{{ {''id'': 1, ''src'':''shellies_discovery'', ''method'':''Shelly.GetConfig''}
      | to_json }}'
    device_ids:
    - shellyplus1-7c87cexxxxxx
- id: shellies_discovery_gen2
  alias: Shellies Discovery Gen2
  description: ''
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: '{{ trigger.payload_json.src }}'
      device_config: '{{ trigger.payload_json.result }}'
  mode: queued
  max: 999
```

**Debug log:**
```txt

```
