### ISSUE TITLE
Troubles making it work

### ISSUE THREAD

**Issue by aabafra** [bieniu/ha-shellies-discovery-gen2#133]
Hi!

I've always manually integrated my Shelly devices into HASS thru MQTT but I'm finding issues with gen2 devices.

I'm trying this script with a device configured like this:

![image](https://user-images.githubusercontent.com/63967859/209820188-41b207fb-12ed-451c-a6bc-0a1e265b33ea.png)

I've added the following 2 automations:

```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids:  # enter the list of device IDs here
      - "shellies/luz-pasillo-techo"
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
```
I have placed the script at python_scripts folder. 

But I don't get it working. Nothing happens at all. 

Any idea where the problem could be?
