### ISSUE TITLE
Shelly Plus 1PM detached switch has no Input sensor available

### ISSUE THREAD

**Issue by Vargash** [bieniu/ha-shellies-discovery-gen2#197]
**Describe the bug**
Shelly Plus 1PM configured in Detached Switch mode does not correctly configure the "Input" sensor, thus being unusable.
![shelly_sensor_error](https://user-images.githubusercontent.com/807174/231395364-de5b65eb-3632-4bc7-a4d1-57cc2c6a887b.png)

**Expected behavior**
When configuring the entity the "Input" sensor should be available

**Versions:**
 - Home Assistant: 2023.4.2
 - Shellies Discovery GEN2: 2.10.0
 - Shelly device firmware: 0.14.1

**Shellies Discovery GEN2 automation:**

```yaml
automation shellies_announce_gen2:
  - alias: "Shellies Announce Gen2"
    trigger:
      - platform: homeassistant
        event: start
    variables:
      device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
      device_ids:  # enter the list of device IDs (MQTT prefixes) here
        - shellyplus2pm-48551998ae20
        - shellyplus2pm-485519a25928
        - shellyplus2pm-485519a295c8
        - shellyplus2pm-485519a27824
        - shellyplus2pm-485519a280a0
        - shellyplus1pm-441793931310
        - shellyplus1pm-a8032ab9d260
        - shellyplus1pm-441793931f00
        - shellyplus1pm-441793950aa8
        - shellyplus1pm-a8032ab2b130
        - shellyplus1pm-441793a4d514
    action:
      - repeat:
          for_each: "{{ device_ids }}"
          sequence:
            - service: mqtt.publish
              data:
                topic: "{{ repeat.item }}/rpc"
                payload: "{{ device_info_payload }}"

automation shellies_discovery_gen2:
  - alias: "Shellies Discovery Gen2"
    mode: queued
    max: 999
    trigger:
      - platform: mqtt
        topic: shellies_discovery/rpc
    action:
      - service: python_script.shellies_discovery_gen2
        data:
          id: "{{ trigger.payload_json.src }}"
          device_config: "{{ trigger.payload_json.result }}"
```

**Debug log:**
[shelly_discovery_g2_logs.txt](https://github.com/bieniu/ha-shellies-discovery-gen2/files/11208820/shelly_discovery_g2_logs.txt)

```txt

```
