### ISSUE TITLE
Package shelly2pm setup failed

### ISSUE THREAD

**Issue by htcheroportugal** [bieniu/ha-shellies-discovery-gen2#208]
**Describe the bug**

**Expected behavior**

i use this configuration:

```
python_script:

# automations.yaml file
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - Shelly
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
```

**Versions:**
 - Home Assistant: last version
 - Shellies Discovery GEN2: last version
 - Shelly device firmware: last version

**Shellies Discovery GEN2 automation:**

```yaml

```

**Debug log:**

```txt

```
