### ISSUE TITLE
Shelly Plus 1 - Stays unkown after HA reboot

### ISSUE THREAD

**Issue by nitobosch** [bieniu/ha-shellies-discovery-gen2#235]
Hi, my two Shelly Plus 1 always stays on an unknown state for all sensors inside it after a HA reboot, until there's a state change on the device, then it's updated. It's not happening on my Shelly Plus 1PM neither Plus 2 PM.

For example:
This is the output sensor:
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/11455488/91474164-ca7d-4a84-8c7b-4940364264e3)

This is the addon digital input sensor:
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/11455488/cbc37538-ff60-4cf4-b73e-8c4644f8c36a)

**Versions:**
 - Home Assistant: 2023.7.1
 - Shellies Discovery GEN2: 2.14.0
 - Shelly device firmware: 0.14.1

**Shellies Discovery GEN2 automation:**
```
alias: Shellies Discovery Gen2
mode: queued
max: 999
trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
      qos: 2
```
