### ISSUE TITLE
Sensors values not updated / unknown after homeassistant restart

### ISSUE THREAD

**Issue by h3llrais3r** [bieniu/ha-shellies-discovery-gen2#281]
**Describe the bug**
Shelly plus 1 devices announced and discovered via the script.
Sensors, switches, ... are created and I'm able to control the switch from home assistant. 
Also the input change is detected.
However, when I restart home assistant, lot's of sensors become unknown... (screenshot below taken 1h after restart of hass)
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/1945295/e287f8c9-a7f8-4bae-a1b2-7b7543e7daba)

Devices are sending the data, as I see them coming in on the status/rpc topic for every device every 30s.
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/1945295/e3f0dca3-d032-4d53-9bba-54b97f45622b)

Strange thing: If I reboot the shelly device, the sensors seem to be populated with a value, but I don't think it's updating any further...

**Expected behavior**
Sensors are available after home assistant restart

**Versions:**
 - Home Assistant: 2023.9.3
 - Shellies Discovery GEN2:  v2.19.1
 - Shelly device firmware: 1.0.3

**Shellies Discovery GEN2 automation:**

```yaml
###########################################
### Shelly gen2 announce and discovery  ###
###########################################

- id: shelly_gen2_announce
  alias: Shelly gen2 announce
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload: "{{ {'id': 1, 'src':'shellies/shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids: # enter the list of device IDs (MQTT prefixes) here
      - shellies/shellyplus1/garage_door_1
      - shellies/shellyplus1/garage_door_2
      - shellies/shellyplus1/garage_door_3
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"
  mode: single

- id: shelly_gen2_discovery
  alias: Shelly gen2 discovery
  trigger:
    - platform: mqtt
      topic: shellies/shellies_discovery/rpc
  action:
    - service: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
        script_prefix: shellies
  mode: queued
  max: 999

```

**Debug log:**
https://privatebin.net/?36100cd7034a5a8e#D46adV2uW49WnFKQXqYxdvzGdBAVNw6ErSQGaHgvcfdd
