### ISSUE TITLE
Request MQTT support for monophase new option for Shelly Pro 3EM since firmware 1.1.0

### ISSUE THREAD

**Issue by jpatriarca** [bieniu/ha-shellies-discovery-gen2#338]
**Describe the bug**

 With the last update of your script, values are presented for generic information like temperature, firmware, last reboot, etc. But related with values coming from each three named channels, the values are presented as unknown.

**Expected behavior**

 Script support to:
- Detect sys/device/profile value (as monophase and triphase) for Shelly.GetStatus or Shelly.GetConfig
- Reach em1:0, em1:1 and em1:2 names from Shelly.GetConfig and create the correspontent MQTT topics
- Read values for each em1 channel presented in Shelly.GetStatus and write down values to each MQTT topics

**Versions:**
 - Home Assistant: 2023.12.3
 - Shellies Discovery GEN2: 2.24.0
 - Shelly device firmware: 1.1.0

**Shellies Discovery GEN2 automation:**

```
- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
  - service: mqtt.publish
    data:
      topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
      payload: "status_update"
```

**Shelly device MQTT settings:**

**Debug log:**

```
No logs available for the specific issue reported
```
