### ISSUE TITLE
 No all values from PRO1PM and no data, values from PRO4PM

### ISSUE THREAD

**Issue by ltksolutions** [bieniu/ha-shellies-discovery-gen2#357]
**Describe the bug**

**Versions:**
 - Home Assistant: 
 - Core 2024.1.6
 - Supervisor 2023.12.1
 - Operating System 11.4
 - Frontend 20240104.0
 - Shellies Discovery GEN2:  Version 2.26.0
 - Shelly device firmware: PRO4PM version 20231219-133936/1.1.0-g34b5d4f, PRO1PM version 20231219-133937/1.1.0-g34b5d4f

**Shellies Discovery GEN2 automation:**

``` YAML
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:

python_script:

logger:
  default: warning
  logs:
    homeassistant.components.python_script: debug
    homeassistant.components.automation: info
    homeassistant.components.mqtt.discovery: info

```

**Shelly device MQTT settings:**

![1 (6)](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/8642569/001a7715-109f-4098-a120-6094bb56d381)
![4](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/8642569/541c0732-7938-449c-aa15-6aa546f67e0a)
![3](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/8642569/60645d55-f4f3-42f4-a756-c6d93938655a)
![2 (1)](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/8642569/2ce0cee4-9c4a-4c55-a534-10f0da410638)

**Debug log:**
not errors
