### ISSUE TITLE
Shelly 4PM Not showing up after restart

### ISSUE THREAD

**Issue by UMB8998** [bieniu/ha-shellies-discovery-gen2#365]
**Describe the bug**

  After discovering the Shelly the device shows up and we are able to control it, but if I restart the Shelly, it shows as disconnected, even when I rerun the Announce Automation, or even restart HA it still shows as offline.
I connected to the GUI of the Shelly and turn on and of the switch to generate MQTT Messages, they show up in MQTT Explorer but HA still shows the Shelly as Offline.
The Only way to make the Shelly to be online again is manually starting the script in the Shelly,and then running the automation. Other option that we found is setting an MQTT Message with the topic "online" and set it to true.
Also it only happens with Shelly Pro 4PM, we have other gen2 Shellies on the network like Plus 2 and Plus 1 and it works flawlessly

**Expected behavior**

The shelly has to betected as online

**Versions:**
 - Home Assistant: 2024.2.1
 - Shellies Discovery GEN2: 2.26.0
 - Shelly device firmware: We tried with 1.2.0 and 1.1.0

**Shellies Discovery GEN2 automation:**

```yaml
  - id: shellies_announce_gen2
  alias: Shellies Announce Gen2
  trigger:
  - platform: homeassistant
    event: start
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids:
    - shellypro4pm-083af27b39a8
    - shellyplus2pm-90380c385478
- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
  - service: mqtt.publish
    data:
      topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
      payload: "status_update"
```

**Shelly device MQTT settings:**
  
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/35478658/c4d4b71b-0b59-4dba-999b-dfe5d361d541)

**Debug log:**

```txt


```
[home-assistant_2024-02-15T17-17-24.112Z.log](https://github.com/bieniu/ha-shellies-discovery-gen2/files/14300208/home-assistant_2024-02-15T17-17-24.112Z.log)
