### ISSUE TITLE
Shelly Uni Plus is not working correctly

### ISSUE THREAD

**Issue by Spartacus68** [bieniu/ha-shellies-discovery-gen2#368]
**Describe the bug**

Temperature and Humidity Sensor DHT22 will not be discuvered. From time to time all other inputs and potputs disapear

**Expected behavior**

Humidity and Temperature will be transfered to HA

**Versions:**
 - Home Assistant: 
 - Shellies Discovery GEN2: 
 - Shelly device firmware: 

**Shellies Discovery GEN2 automation:**

```
alias: Shellies Discovery Gen2
description: ""
trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
mode: queued
max: 999
```

**Shelly device MQTT settings:**

![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/121975453/6a2b8c4e-68d3-49cf-8e6a-f422392a2709)

**Debug log:**

[home-assistant.log](https://github.com/bieniu/ha-shellies-discovery-gen2/files/14318747/home-assistant.log)
