### ISSUE TITLE
Shelly i4 not discovered

### ISSUE THREAD

**Issue by emkookmer** [bieniu/ha-shellies-discovery-gen2#38]
I Have 2 Shelly I4's which i've configured to use MQTT with both `RPC status notifications over MQTT` and `Generic status update over MQTT` enabled.
I've installed `shellies_discovery_gen2.py` through HACS and added the minimal automations configuration.

I've got the feeling that i'm missing something or forgot to do something.
Could you point me in the right direction ??

**Describe the bug/Problem**

Devices are not showing up in Home Assistant

**Expected behavior**

Devices show up in Home Assistant

**Versions:**
 - Home Assistant: 2021.12.5
 - Shellies Discovery GEN2:  1.1.2
 - Shelly device firmware: 
      Device ID: 083AF2015038
      Firmware version: i4prod1
      Firmware build ID: 20220120-094630/i4prod1-g480b553
      Web build ID: 1.5.5-1729906

**Shellies Discovery GEN2 automation:**

```yaml
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
  action:
    - service: mqtt.publish
      data:
        topic: "shellypro4pm-aabbccddeeff/rpc"  # shellypro4pm-aabbccddeeff is a device ID
        payload: "{{ device_info_payload }}"
    - service: mqtt.publish
      data:
        topic: "shellyplus1pm-112233445566/rpc"  # shellyplus1pm-112233445566 is a device ID
        payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"

- id: shellies_status_gen2
  alias: "Shellies Status Gen2"
  trigger:
  - platform: time_pattern
    minutes: "/15"
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: shellypro4pm-aabbccddeeff/rpc
      payload: "{{ {'id': 1, 'src':'shellypro4pm-aabbccddeeff/status', 'method':'Shelly.GetStatus'} | to_json }}"  # shellypro4pm-aabbccddeeff is a device ID
  - service: mqtt.publish
    data:
      topic: shellyplus1pm-112233445566/rpc
      payload: "{{ {'id': 1, 'src':'shellyplus1pm-112233445566/status', 'method':'Shelly.GetStatus'} | to_json }}"  # shellyplus1pm-112233445566 is a device ID
```

**Debug log:**

```txt

```
