### ISSUE TITLE
NameError: name 'availability' is not defined

### ISSUE THREAD

**Issue by ziurim** [bieniu/ha-shellies-discovery-gen2#39]
**Describe the bug**

I have Shelly Pro 4PM, when I set name for each relay in shelly UI page, then I got exception

**Expected behavior**

I think need move up code https://github.com/bieniu/ha-shellies-discovery-gen2/blob/9595dc6704a0ceafc6827c1f07c61ed729f0e0af/python_scripts/shellies_discovery_gen2.py#L1132-L1143

to https://github.com/bieniu/ha-shellies-discovery-gen2/blob/9595dc6704a0ceafc6827c1f07c61ed729f0e0af/python_scripts/shellies_discovery_gen2.py#L699

**Versions:**
 - Home Assistant: 2022.2.7
 - Shellies Discovery GEN2: 1.1.2
 - Shelly device firmware: 
Device ID: 84CCA87F20F8
Firmware version: 0.9.3
Firmware build ID: 20220117-162030/0.9.3-g354c141
Web build ID: 1.5.5-c01b44e

**Shellies Discovery GEN2 automation:**

```yaml
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
  action:
    - service: mqtt.publish
      data:
        topic: "shellypro4pm-84cca87f20f8/rpc"
        payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"

- id: shellies_status_gen2
  alias: "Shellies Status Gen2"
  trigger:
  - platform: time_pattern
    minutes: "/15"
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: shellypro4pm-84cca87f20f8/rpc
      payload: "{{ {'id': 1, 'src':'shellypro4pm-84cca87f20f8/status', 'method':'Shelly.GetStatus'} | to_json }}"
```

**Debug log:**

```txt
2022-02-16 09:19:44 ERROR (SyncWorker_6) [homeassistant.components.python_script.shellies_discovery_gen2.py] Error executing script: name 'availability' is not defined
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery_gen2.py", line 1160, in <module>
  File "shellies_discovery_gen2.py", line 1032, in configure_device
  File "shellies_discovery_gen2.py", line 777, in get_switch
NameError: name 'availability' is not defined
```
