### ISSUE TITLE
input sensor doesn't update it's state after reboot/reload/offline unless manually triggered

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery-gen2#41]
**Describe the bug**

get status automation triggers the shelly to send a status update.
the output includes the input state , like in this example

```
{
	"id": 1,
	"src": "shellyplus1pm-441793a4ec90",
	"dst": "shellies/balcony-lights/status",
	"result": {
		"ble": {},
		"cloud": {
			"connected": false
		},
		"input:0": {
			"id": 0,
			"state": false
		},
		"mqtt": {
			"connected": true
		},
		"switch:0": {
			"id": 0,
			"source": "MQTT",
			"output": false,
			"apower": 0.0,
			"voltage": 215.3,
			"current": 0.000,
			"aenergy": {
				"total": 0.000,
				"by_minute": [0.000, 0.000, 0.000],
				"minute_ts": 1645549643
			},
			"temperature": {
				"tC": 48.1,
				"tF": 118.6
			}
		},
		"sys": {
			"mac": "441793A4EC90",
			"restart_required": false,
			"time": "18:07",
			"unixtime": 1645549646,
			"uptime": 3061262,
			"ram_size": 249232,
			"ram_free": 180268,
			"fs_size": 458752,
			"fs_free": 229376,
			"cfg_rev": 4,
			"available_updates": {
				"beta": {
					"version": "0.10.0-beta4"
				}
			}
		},
		"wifi": {
			"sta_ip": "xx.xx.xx.xx",
			"status": "got ip",
			"ssid": "xxxxxxxxxxx",
			"rssi": -61
		}
	}
}
```

notice that input state is provided but sensor is not updated.
The sensor is only updated when the input is manually changed on the shelly

similarly the announce script with "get config" returns similar data

**Expected behavior**
the sensor should be update based on the status reported by "get status" or "get config"

**Versions:**
 - Home Assistant:  2022.2.9
 - Shellies Discovery GEN2:  1.1.2
 - Shelly device firmware:  0.9.3

**Shellies Discovery GEN2 automation:**

```yaml
alias: Shellies Discovery Gen2
trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: '{{ trigger.payload_json.src }}'
      device_config: '{{ trigger.payload_json.result }}'
mode: queued
max: 999

alias: Shellies Announce Gen2
trigger:
  - platform: homeassistant
    event: start
action:
  - service: mqtt.publish
    data:
      topic: shellies/garden-pro4/rpc
      payload: '{{ device_info_payload }}'
  - service: mqtt.publish
    data:
      topic: shellies/office-switch/rpc
      payload: '{{ device_info_payload }}'
  - service: mqtt.publish
    data:
      topic: shellies/balcony-lights/rpc
      payload: '{{ device_info_payload }}'
variables:
  device_info_payload: >-
    {{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} |
    to_json }}


alias: Shellies Status Gen2
trigger:
  - platform: time_pattern
    minutes: /15
  - platform: homeassistant
    event: start
action:
  - service: mqtt.publish
    data:
      topic: shellies/garden-pro4/rpc
      payload: >-
        {{ {'id': 1, 'src':'shellies/garden-pro4/status',
        'method':'Shelly.GetStatus'} | to_json }}
  - service: mqtt.publish
    data:
      topic: shellies/office-switch/rpc
      payload: >-
        {{ {'id':1, 'src': 'shellies/office-switch/status',
        'method':'Shelly.GetStatus'} | to_json }}
  - service: mqtt.publish
    data:
      topic: shellies/balcony-lights/rpc
      payload: >-
        {{ {'id':1, 'src': 'shellies/balcony-lights/status',
        'method':'Shelly.GetStatus'} | to_json }}

```
