### ISSUE TITLE
Adding multiple Shelly BLU TRVs to single Shelly Gateway GEN3

### ISSUE THREAD

**Issue by gu-stera** [bieniu/ha-shellies-discovery-gen2#498]
I've added a GW3 to my setup with 2 BLU TRVs connected to it. I see the GW added in MQTT, but the TRVs are not showing up.

Here is my config:
```
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - LR-GW3 # This GW doesn't show the 2 TRVs that are connected to it
      - KTCN-GW3 # This GW shows the TRV that is connected to it
      - BR-GW3 # This GW shows the TRV that is connected to it
```
All GWs have the same configuration.

**Comment by bieniu** [comment]
Please fill up the form. I'm not able to help you without any information.

**Comment by gu-stera** [comment]
**Describe the bug**


**Expected behavior**



**Versions:**
 - Home Assistant: Home Assistant OS 13.2, supervisor-2024.10.2, core-2024.10.3
 - Shellies Discovery GEN2: 3.2.0
 - Shelly device firmware: 20241021-140344/1.4.99-blugwg3prod4-g110402b
 - 20241011-050134/v1.0.1@ed260994

**Shellies Discovery GEN2 automations:**
```yaml
 - id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  triggers:
    - platform: homeassistant
      event: start
  variables:
    get_config_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}"
    get_components_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents'} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - LR-GW3
      - KTCN-GW3
      - BR-GW3
  actions:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_config_payload }}"
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_components_payload }}"

```

```yaml
- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  triggers:
    - platform: mqtt
      topic: shellies_discovery/rpc
  actions:
    - action: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
    - condition: template
      value_template: "{{ 'mqtt' in trigger.payload_json.result }}"
    - service: mqtt.publish
      data:
        topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
        payload: "status_update"
```
