### ISSUE TITLE
Add sensors from `Shelly.GetStatus` payload

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery-gen2#5]
hello,

the script works well but i see several sensors missing.

here is an example of the manual mqtt entities i created that i hope you'll add in the script.
For that you need to add an automation to get status.

**Automation Get Status**
```
alias: Shellies Get Status
description: ''
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
condition: []
action:
  - service: mqtt.publish
    data:
      topic: shellyplus1pm-112233/rpc
      payload: >-
        {"id":1, "src": "shellies_discovery/shellyplus1pm-112233",  "method":"Shelly.GetStatus"}
mode: single
```

**Binary Sensors**
```
- platform: mqtt
  name: "Shelly Plus 1PM Input 0"
  unique_id: binary_sensor.shelly_plus_1pm_input_0
  value_template: "{{ value_json.state }}"
  payload_on: "True"
  payload_off: "False"
  state_topic: shellyplus1pm-112233/status/input:0


- platform: mqtt  
  name: "Shelly Plus 1PM Firmware Update"
  unique_id: binary_sensor.shelly_plus_1pm_firmware_update
  device_class: update
  state_topic: shellies_discovery/shellyplus1pm-112233/rpc
  value_template: >
    {%- if value_json.result.sys.available_updates.stable is defined %}
    ON
    {%- else %}
    OFF
    {%- endif %}
  json_attributes_topic: shellies_discovery/shellyplus1pm-112233/rpc
  json_attributes_template: >
    {%- if value_json.result.sys.available_updates.stable is defined %}
    {{ value_json.result.sys.available_updates.stable | tojson }}
    {%- endif %}
```

**Sensor**
```
- platform: mqtt
  name: "Shelly Plus 1PM Uptime"
  unique_id: sensor.shelly_plus_1pm_uptime
  device_class: timestamp
  state_topic: shellies_discovery/shellyplus1pm-112233/rpc
  value_template: "{{(as_timestamp(now())-value_json.result.sys.uptime)|timestamp_local}}"

- platform: mqtt
  name: "Shelly Plus 1PM IP"
  unique_id: sensor.shelly_plus_1pm_ip
  icon: mdi:ip-outline
  state_topic: shellies_discovery/shellyplus1pm-112233/rpc
  value_template: "{{ value_json.result.wifi.sta_ip }}"
  
- platform: mqtt
  name: "Shelly Plus 1PM SSID"
  unique_id: sensor.shelly_plus_1pm_ssid
  icon: mdi:wifi
  state_topic: shellies_discovery/shellyplus1pm-112233/rpc
  value_template: "{{ value_json.result.wifi.ssid }}"

- platform: mqtt
  name: "Shelly Plus 1PM RSSI"
  unique_id: sensor.shelly_plus_1pm_rssi
  unit_of_measurement: dBm
  device_class: signal_strength
  state_topic: shellies_discovery/shellyplus1pm-112233/rpc
  value_template: "{{ value_json.result.wifi.rssi }}"
```
