### ISSUE TITLE
H&T Devices are not discovered

### ISSUE THREAD

**Issue by Spartacus68** [bieniu/ha-shellies-discovery-gen2#504]
**Describe the bug**

as metioned, H&T devices are not discovered by the latest update

**Expected behavior**
 automations  shellies_announce_gen2 and discoveryGen2 have been updated to the latest version but bthome devices are not present in HA.

**Versions:**
 - Home Assistant: 2024.10.3
 - Shellies Discovery GEN2: 3.3.0
 - Shelly device firmware: 1.4.4

**Shellies Discovery GEN2 automations:**

```yaml
id: shellies_discovery_gen2
alias: "Shellies Discovery Gen2"
mode: queued
max: 999
triggers:
  - platform: mqtt
    topic: shellies_discovery/rpc
actions:
  - action: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
  - condition: template
    value_template: "{{ 'mqtt' in trigger.payload_json.result }}"
  - service: mqtt.publish
    data:
      topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
      payload: "status_update"
```

```yaml
id: shellies_announce_gen2
alias: "Shellies Announce Gen2"
triggers:
  - platform: homeassistant
    event: start
actions:
  - repeat:
      for_each: "{{ device_ids }}"
      sequence:
        - action: mqtt.publish
          data:
            topic: "{{ repeat.item }}/rpc"
            payload: "{{ get_config_payload }}"
        - service: mqtt.publish
          data:
            topic: "{{ repeat.item }}/rpc"
            payload: "{{ get_components_payload }}"
variables:
  get_config_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}"
  get_components_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents'} | to_json }}"
  device_ids:  # enter the list of device IDs (MQTT prefixes) here
    - wc
    - bad
 ```

shelly devices bad and wc are discovered by HA correctley, only components are missing. You mentioned in V3.0 the update of automations, and the two files above in the automations.yaml have been updated. What else is necessary and what are you meaning with update automations required if you do net refer to the announceGen and discoveryGen2
