### ISSUE TITLE
Discovery of 2pm device not working

### ISSUE THREAD

**Issue by lusluslus** [bieniu/ha-shellies-discovery-gen2#508]
**Describe the bug**
I followed the instructions at https://github.com/bieniu/ha-shellies-discovery-gen2/blob/master/README.md to install and configure Shellies Discovery Gen2

I already had gen1 devices setup through the other script.

I copy and pasted the config and modifed the device-id to match mine. See config below. 

After restarting homeassistant nothing happened, I enabled the debug logging but it didn't say anything useful, it triggered the  `shellies_discovery_gen2` but it didn't do anything beyond that. 

I ran mqtt explorer to see what was going on. I could see my device was sending messages under its own topic, but it was not configured as a homeassistant device. 

I then looked at the automation to see what had happend there, and I noticed that it tried to execute it and failed
![image](https://github.com/user-attachments/assets/84e70dc9-3417-4991-9891-1a4c228094d2)
![image](https://github.com/user-attachments/assets/17de9a77-6571-4ef7-9fd0-c44d94f31bee)

Next I went to mqtt explorer and tried to manually send the `{'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'}` payload to `shellyplus2pm-08b61fccde74/rpc` to see if it would trigger the script and what the result would be. To my surprise it triggered the full setup flow and the device was successfully configured!

I think there is a bug in the instructions and/or that the automation with multiple mqtt publish action at once is causing it to fail. I see that there was a recent update to the instructions in https://github.com/bieniu/ha-shellies-discovery-gen2/pull/483 and I suspect that this broke something.

**Expected behavior**
That it would get recognized automatically once added to `device_ids` 

**Versions:**
 - Home Assistant: 2024.10.3
 - Shellies Discovery GEN2: 3.3.0
 - Shelly device firmware: 20241011-114448/1.4.4-g6d2a586

**Shellies Discovery GEN2 automations:**

```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  triggers:
    - platform: homeassistant
      event: start
  variables:
    get_config_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}"
    get_components_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents'} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - shellyplus2pm-08b61fccde74
  actions:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_config_payload }}"
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_components_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  triggers:
    - platform: mqtt
      topic: shellies_discovery/rpc
  actions:
    - condition: template
      value_template: "{{ 'mqtt' in trigger.payload_json.result }}"
    - action: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
    - service: mqtt.publish
      data:
        topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
        payload: "status_update"
```

**Shelly device MQTT settings:**
![Screenshot from 2024-10-29 13-15-41](https://github.com/user-attachments/assets/a62c5d00-689c-4ea7-b66d-114e59842d9a)

**Debug log:**

Please not that this log is *after* I got it to work so it will show the device as a homeassistant device
[home-assistant.log](https://github.com/user-attachments/files/17556808/home-assistant.log)

**Comment by bieniu** [comment]
MQTT integration discovered your devices
```
[homeassistant.components.mqtt.discovery] Found new component: sensor shellyplus2pm-08b61fccde74-0-power_factor from external application Shellies Discovery Gen2, version: 3.3.0, support URL: https://github.com/bieniu/ha-shellies-discovery-gen2
```

**Comment by lusluslus** [comment]
Yes, but only after I *manually* broadcasted the mqtt message `{'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'}`

I think there is something wrong with the HA automation scripts that makes it not work automatically

**Comment by bieniu** [comment]
Probably MQTT component is not ready when announce automation starts, you can check the trace for this automation and you can add some delay. From my point of view the script is working properly.

**Comment by lusluslus** [comment]
Thanks, I doubt it's the MQTT component though. 

Here is a full reproduction when adding a 3rd device 

First I'm setting mqtt setttings on the shelly
![shelly-mqtt-b0b4](https://github.com/user-attachments/assets/102336a8-ecc4-426e-a504-b6c135e673e4)

It shows up in mqtt-explorer:
![mqtt-explorer-hello-b0b4](https://github.com/user-attachments/assets/5819d394-ef57-4286-8689-ef51a1b630c2)

Next I update automations.yaml with this:
```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  triggers:
    - platform: homeassistant
      event: start
  variables:
    get_config_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}"
    get_components_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents'} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - shellyplus2pm-80646fcfb0b4
  actions:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_config_payload }}"
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_components_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  triggers:
    - platform: mqtt
      topic: shellies_discovery/rpc
  actions:
    - action: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
    - condition: template
      value_template: "{{ 'mqtt' in trigger.payload_json.result }}"
    - service: mqtt.publish
      data:
        topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
        payload: "status_update"
```

Reboot HA, here is the full log (I also set automation to DEBUG)
[home-assistant.log](https://github.com/user-attachments/files/17573395/home-assistant.log)

When I look in mqtt-explorer I see both messages successfully sent through the automation:
![mqtt-explorer-sent-b0b4](https://github.com/user-attachments/assets/219c08f8-509f-4f4f-bc3b-6be6015b321b)

I also see the responses coming back to `shellies_discovery/rpc`
![image](https://github.com/user-attachments/assets/464519c8-e454-41f4-89cb-e4301fbd1465)

That's where the trail stops, for some reason that response doesn't trigger.

Is it simple as needing to load the discovery script before the annonce script?
