### ISSUE TITLE
MQTT integration does not detect the devices

### ISSUE THREAD

**Issue by BenGeba** [bieniu/ha-shellies-discovery-gen2#520]
**Describe the bug**
It's probably not a real bug but a mistake on my part. 
The data all arrive in the MQTT broker and are also updated. I can see temperature values, etc. However, the MQTT integration does not detect the new entities.

**Expected behavior**
The MQTT integration shows the new entities

**Versions:**
 - Home Assistant: 2024.11.1
 - Shellies Discovery GEN2: 3.5.2
 - Shelly device firmware: 
   - Shelly BLU Gateway Gen3: 20241021-140344/1.4.99-blugwg3prod4-g110402b
   - 2x Shelly BLU TRV: 20241011-050134/v1.0.1@ed260994

**Shellies Discovery GEN2 automations:**

```yaml
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  triggers:
    - platform: homeassistant
      event: start
  variables:
    get_config_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}"
    get_components_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents'} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - blu-gateway-kitchen
  actions:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_config_payload }}"
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_components_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  triggers:
    - platform: mqtt
      topic: shellies_discovery/rpc
  actions:
    - action: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
    - condition: template
      value_template: "{{ 'mqtt' in trigger.payload_json.result }}"
    - service: mqtt.publish
      data:
        topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
        payload: "status_update"
```

**Shelly device MQTT settings:**

**Debug log:**

[home-assistant.log](https://github.com/user-attachments/files/17756925/home-assistant.log)
