### ISSUE TITLE
Shellies Discovery Gen2 - Shelly1plus v0.10.0

### ISSUE THREAD

**Issue by ichinm** [bieniu/ha-shellies-discovery-gen2#53]
**Describe the bug**
Hello, 
I tried the script gen1, it works fine.
With Shelly1plus I tried the gen2 and no device found.
RPC status notifications over MQTT: enabled
Generic status update over MQTT: enabled

**Default MQTT data from device**
only 3 topics:

shellyplus1-4417939458e0/events/rpc={"src":"shellyplus1-4417939458e0","dst":"shellyplus1-4417939458e0/events","method":"NotifyStatus","params":{"ts":1647610358.90,"sys":{"available_updates":{}}}}

shellyplus1-4417939458e0/status/switch:0={"id":0, "source":"WS_in", "output":true,"temperature":{"tC":37.8, "tF":100.0}}

shellyplus1-4417939458e0/status/sys={"mac":"4417939458E0","restart_required":false,"time":"14:32","unixtime":1647610358,"uptime":71798,"ram_size":239720,"ram_free":166612,"fs_size":458752,"fs_free":225280,"cfg_rev":18,"available_updates":{}}

**Expected behavior**
!!!

**Versions:**
 - Home Assistant: core-2022.3.5  -  supervisor-2022.03.5
 - Shellies Discovery GEN2: 1.1.7
 - Shelly device firmware: 0.10.0
 - Shelly Firmware build ID: 20220308-100547/0.10.0-g4eda0ff

**Shellies Discovery GEN2 automation:**
- id: shellies_announce_gen2
  alias: Shellies Announce Gen2
  trigger:
  - platform: homeassistant
    event: start
  variables:
    device_info_payload: '{{ {''id'': 1, ''src'':''shellies_discovery'', ''method'':''Shelly.GetConfig''}
      | to_json }}'
  action:
  - service: mqtt.publish
    data:
      topic: shellypro4pm-aabbccddeeff/rpc
      payload: '{{ device_info_payload }}'
  - service: mqtt.publish
    data:
      topic: shellyplus1pm-112233445566/rpc
      payload: '{{ device_info_payload }}'
- id: shellies_discovery_gen2
  alias: Shellies Discovery Gen2
  trigger:
  - platform: mqtt
    topic: shellyplus1-4417939458e0/events/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: '{{ trigger.payload_json.src }}'
      device_config: '{{ trigger.payload_json.result}}'
  mode: queued
  max: 999

**Debug log:**

Logger: homeassistant.components.python_script.shellies_discovery_gen2.py
Source: components/python_script/__init__.py:224
Integration: Python Scripts (documentation, issues)
First occurred: 2:30:12 PM (2 occurrences)
Last logged: 2:30:14 PM

Error executing script: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery_gen2.py", line 1094, in <module>
  File "/usr/local/lib/python3.9/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
TypeError: string indices must be integers

---------------------------------------------------------------------------------------------------------
Logger: homeassistant.helpers.template
Source: helpers/template.py:1822
First occurred: 2:30:12 PM (2 occurrences)
Last logged: 2:30:14 PM

Template variable warning: 'dict object' has no attribute 'result' when rendering '{{ trigger.payload_json.result }}'

**Comment by bieniu** [comment]
I doubt if your device IDs are `shellypro4pm-aabbccddeeff` and `shellyplus1pm-112233445566`. Please configure the automation correctly.

**Comment by cliffkujala** [comment]
Where do we find the device id's? I tried to use the "Device ID" (which is just the MAC address) from the web interface, but that is not working for me either.

**Comment by cliffkujala** [comment]
![003BEFAC-98F2-46AD-90B1-3F4130B8E316](https://user-images.githubusercontent.com/7710215/159367435-3431f0a9-cfd7-4d88-a723-87c53a20c627.jpeg)

**Comment by ichinm** [comment]
Hi, It is used as hostname (find it from your router) and default MQTT prefix

**Comment by ichinm** [comment]
![image](https://user-images.githubusercontent.com/35716624/159368215-6b07227c-7108-4d6e-a09d-9c97193fe3b1.png)

**Comment by cliffkujala** [comment]
Thank you that worked.  Perhaps the documentation should be adjusted to reflect that a customer MQTT name is required and that is what we need to include in the automation configuration.  

I do wish however we didn't need to use customer MQTT names, and I wish we didn't need to manually add each device to the automation.  The Gen1 Shelly announce/discover just automatically creates them with only the minimal configuration.

**Comment by aabafra** [comment]
Hi!

I've always manually integrated my Shelly devices into HASS thru MQTT but I'm finding issues with gen2 devices.

I'm trying this script with a device configured like this:

![image](https://user-images.githubusercontent.com/63967859/209820188-41b207fb-12ed-451c-a6bc-0a1e265b33ea.png)

I've added the following 2 automations:

```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids:  # enter the list of device IDs here
      - "shellies/luz-pasillo-techo"
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
```
I have placed the script at python_scripts folder. 

But I don't get it working. Nothing happens at all. 

Any idea where the problem could be?
