### ISSUE TITLE
Entities not updating

### ISSUE THREAD

**Issue by calvinbui** [bieniu/ha-shellies-discovery-gen2#553]
I can get the relays added, but the entities in Home Assistant are not updating.

When I restart HA, the entities will only show the current state of the relays, such as on or off.

Similar issue to:
- https://github.com/bieniu/ha-shellies-discovery-gen2/issues/104
- https://github.com/bieniu/ha-shellies-discovery-gen2/issues/93

**Expected behavior**

- Entities are updated to reflect the state of the relays

**Versions:**
 - Home Assistant: 2025.1
 - Shellies Discovery GEN2: 3.7.0
 - Shelly device firmware: 1.4.4

**Shellies Discovery GEN2 automations:**

```yaml
---

# https://github.com/bieniu/ha-shellies-discovery-gen2#configuration

- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  triggers:
    - trigger: homeassistant
      event: start
  variables:
    get_config_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}"
    get_components_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents', 'params': {'include': ['config']}} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - shellyplus1pm-441793d4646c # Upstairs Hallway Lights
      - shellyplus1pm-441793942e24 # Garage Lights
      - shellyplus2pm-b0a732485960 # Dining Room Lights
      - shellyplus1pm-7c87ce65d8a0 # Alfresco Lights
  actions:
    - delay:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_config_payload }}"
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_components_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  triggers:
    - trigger: mqtt
      topic: shellies_discovery/rpc
  actions:
    - action: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
    - condition: template
      value_template: "{{ 'mqtt' in trigger.payload_json.result }}"
    - action: mqtt.publish
      data:
        topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
        payload: "status_update"
```

**Shelly device MQTT settings:**

more or less the same between the 4 of them with only prefix and client id different

![image](https://github.com/user-attachments/assets/0b0c8386-f4fd-4088-9934-f40c028ce87c)

**Debug log:**

[homeassistant.components.mqtt.discovery.txt](https://github.com/user-attachments/files/18355466/homeassistant.components.mqtt.discovery.txt)

[homeassistant.components.automation.txt](https://github.com/user-attachments/files/18355467/homeassistant.components.automation.txt)

[homeassistant.components.python_script.shellies_discovery_gen2.py.txt](https://github.com/user-attachments/files/18355468/homeassistant.components.python_script.shellies_discovery_gen2.py.txt)

**Other**:

Using MQTT-Explorer, I can see stuff happening continuously on the relay:

![image](https://github.com/user-attachments/assets/85efc2f4-8e66-4e0d-acbc-7d59611fba06)

Similarly, seeing the relays inside of EMQX

![image](https://github.com/user-attachments/assets/209d81f1-e5b2-4275-bb38-59558edccf69)
