### ISSUE TITLE
Shellies Gen2 are not discovered by Gen2 discovery script

### ISSUE THREAD

**Issue by Simppen** [bieniu/ha-shellies-discovery-gen2#56]
**Describe the bug**

I installed Shellies Discovery Gen2, copied the minimal configuration to Automations.yaml and changed the device IDs.
But it was not working. I have Gen1 script installed and it works fine with all Gen1 Shellies.

**Expected behavior**

I want my two new Shelly Plus 1PM units to appear in the "Entities" list of HA.

**Versions:**
 - Home Assistant: 2021.12.1
 - Shellies Discovery GEN2: 1.1.8
 - Shelly device firmware: 0.7.0

**Shellies Discovery GEN2 automation:**

```
- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"

- id: shellies_status_gen2
  alias: "Shellies Status Gen2"
  trigger:
  - platform: time_pattern
    minutes: "/15"
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: shellyplus1pm-7c87ce644fe4/rpc
      payload: "{{ {'id': 1, 'src':'shellyplus1pm-7c87ce644fe4/status', 'method':'Shelly.GetStatus'} | to_json }}"  # shellyplus1pm-112233445566 is a device ID
  - service: mqtt.publish
    data:
      topic: shellyplus1pm-3c610579c1cc/rpc
      payload: "{{ {'id': 1, 'src':'shellyplus1pm-3c610579c1cc/status', 'method':'Shelly.GetStatus'} | to_json }}"  # shellyplus1pm-112233445566 is a device ID
```

**Debug log:**

https://github.com/bieniu/ha-shellies-discovery-gen2/files/8354783/Logfile_SDGen2.txt
