### ISSUE TITLE
Shelly Pro Dimmer 1/2PM - transition duration not working for light off event

### ISSUE THREAD

**Issue by jortan** [bieniu/ha-shellies-discovery-gen2#584]
**Describe the bug**

  With Shelly Pro Dimmer 2PM - When an automation triggers a "light on" event, the transition duration works as expected.  When an automation triggers a "light off" event, the transition duration is ignored.  This seems to be because for the "light off" event, the transition_duration value is incorrectly placed outside of the "params" json object:

Light on event:
```
{
  "id": 1,
  "src": "home-assistant",
  "method": "Light.Set",
  "params": {
    "id": 1,
    "on": true,
    "transition_duration": 10,
    "brightness": 13
  }
```

Light off event
```
{
  "id": 1,
  "src": "home-assistant",
  "method": "Light.Set",
  "params": {
    "id": 1,
    "on": false
  },
  "transition_duration": 10
}
```

**Expected behavior**

  A light off event should look like this

```
{
  "id": 1,
  "src": "home-assistant",
  "method": "Light.Set",
  "params": {
    "id": 1,
    "on": false
    "transition_duration": 10
  },
}
```

**Versions:**
 - Home Assistant: 2025.2.1
 - Shellies Discovery GEN2: 3.11.0
 - Shelly Pro DImmer 2PM: 1.4.4 / 1.5.0 beta2

**Shellies Discovery GEN2 automations:**

```
- id: shellies_announce_gen2
  alias: Shellies Announce Gen2
  triggers:
  - trigger: homeassistant
    event: start
  variables:
    get_config_payload: '{{ {''id'': 1, ''src'': ''shellies_discovery'', ''method'':
      ''Shelly.GetConfig''} | to_json }}'
    get_components_payload: '{{ {''id'': 1, ''src'': ''shellies_discovery'', ''method'':''Shelly.GetComponents'',
      ''params'': {''include'': [''config'']}} | to_json }}'
    device_ids:
    - shellyprodm2pm-08f9e0e4b8dc
    - shellyprodm2pm-08f9e0e49010
    - shellyprodm2pm-08f9e0e48bf0
    - shellyprodm2pm-08f9e0e4a848
    - shellyprodm2pm-08f9e0e4a978
    - shellyprodm2pm-2cbcbba53ef8
    - shellyprodm2pm-08f9e0e4a180
    - shellyprodm2pm-08f9e0e48ffc
    - shellyprodm2pm-08f9e0e4a2a8
    - shellyprodm2pm-a0dd6c9e5c24
    - shellyprodm2pm-fce8c0d8e558
    - shellyprodm2pm-fce8c0d8c874
    - shellyprodm2pm-a0dd6c9e7f70
    - shellyprodm2pm-a0dd6c9f6058
    - shellyprodm2pm-a0dd6c9f7dd0
    - shellyprodm2pm-a0dd6c9e7b34
    - shellyprodm2pm-fce8c0d8cf48
    - shellyprodm2pm-a0dd6c9f855c
    - shellyprodm2pm-a0dd6c9e6d24
  actions:
  - repeat:
      for_each: '{{ device_ids }}'
      sequence:
      - action: mqtt.publish
        data:
          topic: '{{ repeat.item }}/rpc'
          payload: '{{ get_config_payload }}'
      - action: mqtt.publish
        data:
          topic: '{{ repeat.item }}/rpc'
          payload: '{{ get_components_payload }}'
- id: shellies_discovery_gen2
  alias: Shellies Discovery Gen2
  mode: queued
  max: 999
  triggers:
  - trigger: mqtt
    topic: shellies_discovery/rpc
  actions:
  - action: python_script.shellies_discovery_gen2
    data:
      id: '{{ trigger.payload_json.src }}'
      device_config: '{{ trigger.payload_json.result }}'
  - condition: template
    value_template: '{{ ''mqtt'' in trigger.payload_json.result }}'
  - action: mqtt.publish
    data:
      topic: '{{ trigger.payload_json.result.mqtt.topic_prefix }}/command'
      payload: status_update
```

**Shelly device MQTT settings:**

![Image](https://github.com/user-attachments/assets/b2f65bb1-490e-4fbb-973e-4e009b53a37d)

**Debug log:**

[home-assistant_2025-02-09T13-52-31.282Z.log](https://github.com/user-attachments/files/18724667/home-assistant_2025-02-09T13-52-31.282Z.log)
