### ISSUE TITLE
"model not supported" after each update

### ISSUE THREAD

**Issue by markl3001** [bieniu/ha-shellies-discovery-gen2#592]
**Describe the bug**

After each update, I get this error:
`
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 290, in execute
    exec(compiled.code, restricted_globals)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shellies_discovery_gen2.py", line 4865, in <module>
ValueError: model ShellyPlus1PM is not supported, please open a feature request here https://github.com/bieniu/ha-shellies-discovery-gen2/issues
`

I then have to change line 4863 (in version 3.11.1) from 
`model = device_id.rsplit("-", 1)[0]`
to
`model = device_id.rsplit("-", 1)[0].lower()`

and then it works again.


**Expected behavior**
<!--
  A clear and concise description of what you expected to happen.
-->
The script should work without adaptions after each update.


**Versions:**
 - Home Assistant: 2025.2.1
 - Shellies Discovery GEN2: 3.11.1
 - Shelly device firmware: 20241011-114445/1.4.4-g6d2a586


**Shellies Discovery GEN2 automations:**
<!--
  Please provide Shellies Discovery automations (announce and discovery) here.
-->

```yaml
- id: shellies_announce_gen2
  alias: Shellies Announce Gen2
  triggers:
  - trigger: homeassistant
    event: start
  variables:
    get_config_payload: '{{ {''id'': 1, ''src'': ''shellies_discovery'', ''method'':
      ''Shelly.GetConfig''} | to_json }}'
    get_components_payload: '{{ {''id'': 1, ''src'': ''shellies_discovery'', ''method'':''Shelly.GetComponents'',
      ''params'': {''include'': [''config'']}} | to_json }}'
    device_ids:
    - shelly-photovoltaik
    - shelly-stiegenhaus
    - shelly-vorraum-oben
    - shelly-evu-sperre
    - shelly-kloumschalter
    - shelly-batteriecontroller
    - shelly-batterierelais
    - shelly-temperatur1
    - shelly-kueche
    - shelly-plug1
    - shelly-wohnzimmer
    - shelly-plug2
    - shelly-entfeuchter
    - shelly-luefter
    - shelly-schlafzimmerrollo
  actions:
  - repeat:
      for_each: '{{ device_ids }}'
      sequence:
      - action: mqtt.publish
        data:
          topic: '{{ repeat.item }}/rpc'
          payload: '{{ get_config_payload }}'
      - action: mqtt.publish
        data:
          topic: '{{ repeat.item }}/rpc'
          payload: '{{ get_components_payload }}'
- id: shellies_discovery_gen2
  alias: Shellies Discovery Gen2
  mode: queued
  max: 999
  triggers:
  - trigger: mqtt
    topic: shellies_discovery/rpc
  actions:
  - action: python_script.shellies_discovery_gen2
    data:
      id: '{{ trigger.payload_json.src }}'
      device_config: '{{ trigger.payload_json.result }}'
  - condition: template
    value_template: '{{ ''mqtt'' in trigger.payload_json.result }}'
  - action: mqtt.publish
    data:
      topic: '{{ trigger.payload_json.result.mqtt.topic_prefix }}/command'
      payload: status_update

```


**Shelly device MQTT settings:**
<!--
  Please provide a screenshot of the Settings -> MQTT section from the device's WebUI (not from Shelly app!).
-->

![Image](https://github.com/user-attachments/assets/c736e704-f0b1-4cc7-a8c9-52d2a378852a)


**Debug log:**
<!--
  Please provide a log file for the following logger configuration:
  logger:
    default: error
    logs:
      homeassistant.components.python_script: debug
      homeassistant.components.automation: info
      homeassistant.components.mqtt.discovery: info
-->

```txt
N//A
```
