### ISSUE TITLE
Values listed as unknown when Shelly Pro 3EM-3CT63 is configured as monophase device profile.

### ISSUE THREAD

**Issue by gijbelsy** [bieniu/ha-shellies-discovery-gen2#621]
**Describe the bug**
The sensor values are listed as unknown (or unavailable) in the MQTT integration of Home Assistant.
This only happens when the device is configured in monophase mode.
In 3-phase mode the values are listed correctly.

**Expected behavior**
List values correctly when the device is configured in monophase mode.

**Versions:**
 - Home Assistant: 2025.4.1
 - Shellies Discovery GEN2: 
 - Shelly device firmware: 1.51
 - Shelly device: Pro 3 EM

**Shellies Discovery GEN2 automations:**

```yaml
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  triggers:
    - trigger: homeassistant
      event: start
  variables:
    get_config_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}"
    get_components_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents', 'params': {'include': ['config']}} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - shellypro3em63-defaultdevid1maskedforsecurity
      - shellypro3em63-defaultdevid2maskedforsecurity
  actions:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_config_payload }}"
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_components_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  triggers:
    - trigger: mqtt
      topic: shellies_discovery/rpc
  actions:
    - action: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
    - condition: template
      value_template: "{{ 'mqtt' in trigger.payload_json.result }}"
    - action: mqtt.publish
      data:
        topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
        payload: "status_update"
```

**Shelly device MQTT settings:**
MQTT is enabled, device is communicating (verified with MQTT explorer).
Enable MQTT control, Enable RPC, RPC status and Generic status updates are checked.
MQTT prefix is left default.
