### ISSUE TITLE
Dict object' has no attribute 'payload_json'

### ISSUE THREAD

**Issue by kagstrom2100** [bieniu/ha-shellies-discovery-gen2#640]
**Describe the bug**
When trying to discover my Shelly devices with the "Shellies Discovery Gen2" automation it always fails 
with the error: `Error: Error rendering data template: UndefinedError: 'dict object' has no attribute 'payload_json'`.

**Expected behavior**
The automation should work without errors and the device should show up.

**Versions:**
 - Home Assistant: 2025.5.2
 - Shellies Discovery GEN2: 
 - Shelly device firmware: 20250508-110646/1.6.1-g8dbd358

**Shellies Discovery GEN2 automations:**
```yaml
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  triggers:
    - trigger: homeassistant
      event: start
  variables:
    get_config_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}"
    get_components_payload: "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents', 'params': {'include': ['config']}} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - shellyplussmoke-hallway
  actions:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_config_payload }}"
          - action: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ get_components_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  triggers:
    - trigger: mqtt
      topic: shellies_discovery/rpc
  actions:
    - action: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
    - condition: template
      value_template: "{{ 'mqtt' in trigger.payload_json.result }}"
    - action: mqtt.publish
      data:
        topic: "{{ trigger.payload_json.result.mqtt.topic_prefix }}/command"
        payload: "status_update"
```

**Shelly device MQTT settings:**
[https://i.imgur.com/R2AohTp.png](https://i.imgur.com/R2AohTp.png)

**Screenshot of the error:**
[https://i.imgur.com/OCItdyL.png](https://i.imgur.com/OCItdyL.png)

**Debug log:**
```2025-05-17 12:39:02.708 INFO (MainThread) [homeassistant.components.automation.wardrobe_turn_on_lights_on_motion] Initialized trigger Wardrobe - Turn on Lights on Motion

2025-05-17 12:39:02.708 INFO (MainThread) [homeassistant.components.automation.wardrobe_turn_off_lights] Initialized trigger Wardrobe - Turn off Lights on no motion

2025-05-17 12:39:02.708 INFO (MainThread) [homeassistant.components.automation.at_sunset] Initialized trigger At Sunset

2025-05-17 12:39:02.709 INFO (MainThread) [homeassistant.components.automation.new_automation] Initialized trigger Turn Off Guest Bedroom Lights With Linus PC

2025-05-17 12:39:02.709 INFO (MainThread) [homeassistant.components.automation.at_sunrise] Initialized trigger At Sunrise

2025-05-17 12:39:02.709 INFO (MainThread) [homeassistant.components.automation.turn_on_guestroom_lights_with_linus_pc] Initialized trigger Turn On GuestRoom lights with Linus PC

2025-05-17 12:39:02.710 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Running automation actions

2025-05-17 12:39:02.710 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeating sequence: Iteration 1 of 1 with item: 'shellyplussmoke-hallway'

2025-05-17 12:39:02.710 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Running automation actions

2025-05-17 12:39:02.710 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Executing step call service

2025-05-17 12:39:02.711 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Initialized trigger Shellies Announce Gen2

2025-05-17 12:39:02.711 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Initialized trigger Shellies Discovery Gen2

2025-05-17 12:39:02.716 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Executing step call service

2025-05-17 12:39:25.854 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Running automation actions

2025-05-17 12:39:25.854 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Executing step call service

2025-05-17 12:39:25.854 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'payload_json' when rendering '{{ trigger.payload_json.src }}'

2025-05-17 12:39:25.855 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'dict object' has no attribute 'payload_json'

2025-05-17 12:39:25.855 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Error while executing automation automation.shellies_discovery_gen2: Error rendering data template: UndefinedError: 'dict object' has no attribute 'payload_json'

2025-05-17 12:39:33.028 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Running automation actions

2025-05-17 12:39:33.028 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Executing step call service

2025-05-17 12:39:33.028 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'payload_json' when rendering '{{ trigger.payload_json.src }}'

2025-05-17 12:39:33.028 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'dict object' has no attribute 'payload_json'

2025-05-17 12:39:33.028 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Error while executing automation automation.shellies_discovery_gen2: Error rendering data template: UndefinedError: 'dict object' has no attribute 'payload_json'
