### ISSUE TITLE
Shelly Pro2 unknown state until turned on

### ISSUE THREAD

**Issue by davidw3591** [bieniu/ha-shellies-discovery-gen2#69]
**Describe the bug**
I have a Shelly Pro4PM and a Shelly Pro2 in my house. After a HomeAssistant reboot the Shelly Pro2 entities are unknown while the Pro4PM are updated.

The light entities of the Pro2 have the state 'unavailable' under /developer-tools/state. But they are available.

![Schermafbeelding 2022-06-23 165959 PNG](https://user-images.githubusercontent.com/22191954/175333878-5ba45f8b-2687-4ae8-b643-a111e4e0b66a.jpg)

When I click the "off lightning bolt" in HASS, it does nothing. When clicking the "on lightning bolt" the light turns on and HASS shows a toggle button instead of the lightning bolts. Then everything works normal.

When turning the lights on in the Shelly device UI, the lightning bolts also changes to a toggle button with the right feedback.

**Expected behavior**
Shelly Pro2 entity state gets updated after Shelly Discovery script has run.

**Versions:**
 - Home Assistant: 2022.6.6
 - Shellies Discovery GEN2: 1.1.11
 - Shelly device firmware: 0.10.3

**Shellies Discovery GEN2 automation:**

```
##################################################
## Automation
##################################################
automation:
  - alias: "Shelly Discovery Gen 2 - Announce"
    trigger:
      - platform: homeassistant
        event: start
    variables:
      device_info_payload: "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    action:
      # Pro4PM
      - service: mqtt.publish
        data:
          topic: "shellypro4pm-84cca87e3f84/rpc"
          payload: "{{ device_info_payload }}"

      # Pro2
      - service: mqtt.publish
        data:
          topic: "shellypro2-30c6f784b9b8/rpc"
          payload: "{{ device_info_payload }}"

  ##########

  - alias: "Shelly Discovery Gen 2 - Run discovery python script"
    mode: queued
    max: 999
    trigger:
      - platform: mqtt
        topic: shellies_discovery/rpc
    action:
      - service: python_script.shellies_discovery_gen2
        data:
          id: "{{ trigger.payload_json.src }}"
          device_config: "{{ trigger.payload_json.result }}"

  ##########

  - alias: "Shelly Discovery Gen 2 - Status"
    trigger:
      - platform: time_pattern
        minutes: "/15"

      - platform: homeassistant
        event: start
    action:
      # Pro4PM
      - service: mqtt.publish
        data:
          topic: shellypro4pm-84cca87e3f84/rpc
          payload: "{{ {'id': 1, 'src':'shellypro4pm-84cca87e3f84/status', 'method':'Shelly.GetStatus'} | to_json }}"

      # Pro2
      - service: mqtt.publish
        data:
          topic: shellypro2-30c6f784b9b8/rpc
          payload: "{{ {'id': 1, 'src':'shellypro2-30c6f784b9b8/status', 'method':'Shelly.GetStatus'} | to_json }}"


```

**Debug log:**
[hass_log.txt](https://github.com/bieniu/ha-shellies-discovery-gen2/files/8968565/hass_log.txt)
