### ISSUE TITLE
Shelly Plug US (Plus) Not Supported

### ISSUE THREAD

**Issue by HarrisonWilson** [bieniu/ha-shellies-discovery-gen2#79]
**Describe the bug**

Have new Shelly Plug Plus US. Logs confirm that this is not a supported model.

**Expected behavior**

Support for [Shelly Plug US](https://shelly.cloud/products/shelly-plug-us-smart-home-automation-device/)

**Versions:**
 - Home Assistant: 2022.7.0
 - Shellies Discovery GEN2: 1.2.0
 - Shelly device firmware: plugusprod2

**Shellies Discovery GEN2 automation:**

```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids:  # enter the list of device IDs here
      - shellyplugus-XXXXXXXXXXXXX
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"

```

**Debug log:**

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery_gen2.py", line 1098, in <module>
ValueError: model shellyplugus is not supported, please open an issue here https://github.com/bieniu/ha-shellies-discovery-gen2/issues
```
