### ISSUE TITLE
Shelly Plus 1 PM - Missing Information

### ISSUE THREAD

**Issue by miamilabs** [bieniu/ha-shellies-discovery-gen2#84]
**Describe the bug**

Shelly Plus 1 PM is missing Information for Temp, Voltage, Current. 
The Information is shown as "unknown" even if the information is available in MQTT.

**Expected behavior**

The Device in Home Assistant show Information for Temperature, Volgage, Temperature

**Versions:**
 - Home Assistant: core-2022.7.7
 - Shellies Discovery GEN2: Latest
 - Shelly device firmware: 0.10.3

**Shellies Discovery GEN2 automation:**

```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids:  # enter the list of device IDs here
      - shellyplus1-<censored>
      - shellyplus1-<censored>
      - shellyplus1-<censored>
      - shellyplus1-<censored>
      - shellyplus1pm-balcony-3
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
     
```

**Debug log:**

The are no logs output for the "gen2" script. I get only output for the gen 1.

**MQTT log:**
`
2022-08-02 12:18:39 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on shellyplus1pm-balcony-3/status/rpc: b'{"result":{"wifi":{"rssi":-79,"ssid":"WiFiName","status":"got ip","sta_ip":"IP-Censord"},"sys":{"available_updates":{"beta":{"version":"0.11.0-beta2"}},"cfg_rev":15,"fs_free":217088,"fs_size":458752,"ram_free":162764,"ram_size":239436,"uptime":52890,"unixtime":1659431918,"time":"12:18","restart_required":false,"mac":"censored"},"switch:0":{"temperature":{"tF":137.200000,"tC":58.400000},"aenergy":{"minute_ts":1659431916,"by_minute":[0,0,0],"total":2.387000},"current":0,"voltage":219.600000,"apower":0,"output":false,"source":"MQTT","id":0},"script:1":{"running":true,"id":1},"mqtt":{"connected":true},"input:0":{"state":false,"id":0},"cloud":{"connected":false},"ble":{}}}'
`
