### ISSUE TITLE
devices not available after restart Home Assistant

### ISSUE THREAD

**Issue by geert36** [bieniu/ha-shellies-discovery-gen2#87]
**Describe the bug**
After a restart of Home Assistant the Shelly devices stay unavailable. After a restart of the Shelly devices the devices are available again.

**Expected behavior**
After a restart of Home Assistant the Shelly devices are available.

**Versions:**
 - Home Assistant 2022.8.3
   - Supervisor 2022.07.0
   - Operating System 8.4
   - Frontend 20220802.0 - latest
 - Shellies Discovery GEN2: 1.4.0
 - Shelly device firmware: 20220617-112029/0.10.3-g7c89a05

**Shellies Discovery GEN2 automation:**

```
- id: shellies_announce_gen2
  alias: Shellies Announce Gen2
  trigger:
  - platform: homeassistant
    event: start
  variables:
    device_info_payload: '{{ {''id'': 1, ''src'':''shellies_discovery'', ''method'':''Shelly.GetConfig''}
      | to_json }}'
    device_ids:
    - Shelly Tuinberegening Kleppen
    - Shelly Tuinberegening Pomp
  action:
  - repeat:
      for_each: '{{ device_ids }}'
      sequence:
      - service: mqtt.publish
        data:
          topic: '{{ repeat.item }}/rpc'
          payload: '{{ device_info_payload }}'
- id: shellies_discovery_gen2
  alias: Shellies Discovery Gen2
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: '{{ trigger.payload_json.src }}'
      device_config: '{{ trigger.payload_json.result }}'

```
